apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: orders-trigger
  namespace: warehouse
spec:
  filter:
    attributes:
      type: warehouse.order.v1
      # type: dev.knative.kafka.event 
      # source: /apis/v1/namespaces/warehouse/kafkasources/orders-kafka-source#orders
  broker: default
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: orders-service