apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: orders-service
  namespace: warehouse
spec:
  template:
    spec:
      containers:
        - image: quay.io/famargon/orders-processor-function-event-driven:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              value: orders-processor-serverless
            - name: STOCKS_SVC
              value: stocks-service
---
apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-orders-service
  namespace: warehouse
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: orders-service