---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warehouse-service
  name: warehouse-service
  namespace: warehouse
spec:
  # replicas: ${REPLICAS}
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      serviceAccount: warehouse
      containers:
      - image: quay.io/famargon/warehouse-cloudevents-backend-event-driven:latest
        imagePullPolicy: Always
        name: warehouse-service
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STOCKS_SVC
            value: stocks-service
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8082
          initialDelaySeconds: 1
          periodSeconds: 15
          timeoutSeconds: 7
---
apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-warehouse-service
  namespace: warehouse
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: default
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: warehouse-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: warehouse-service
  name: warehouse-service
  namespace: warehouse
spec:
  ports:    
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: app
  - port: 80
    protocol: TCP
    targetPort: 8082
    name: http
  selector:
    app: warehouse-service
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: warehouse 
  namespace: warehouse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: warehouse
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: warehouse
  namespace: warehouse 
subjects:
- kind: ServiceAccount 
  name: warehouse
  namespace: warehouse 
roleRef:
  kind: ClusterRole
  name: warehouse 
  apiGroup: rbac.authorization.k8s.io
