apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: knative-eventing
data:
  bootstrap.servers: eventing-broker-kafka-bootstrap.kafka:9092
  default.topic.partitions: "1"
  default.topic.replication.factor: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-br-defaults
  namespace: knative-eventing
data:
  default-br-config: |
    clusterDefault:
      brokerClass: Kafka
      apiVersion: v1
      kind: ConfigMap
      name: kafka-broker-config
      namespace: knative-eventing
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: warehouse