apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: orders-kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - warehouse-kafka-kafka-bootstrap.warehouse:9092 # note the kafka namespace
  topics:
  - orders
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default