apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: orders-service
  namespace: warehouse
spec:
  template:
    spec:
      containers:
        - image: quay.io/famargon/orders-processor-function-event-driven:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: warehouse-kafka-kafka-bootstrap:9092
            - name: POD_NAME
              value: orders-processor-serverless
            - name: STOCKS_SVC
              value: stocks-service