apiVersion: sources.knative.dev/v1alpha2
kind: PingSource 
metadata:
  name: orders-service-test-ping-source
spec: 
  schedule: "*/1 * * * *"
  jsonData: '{"itemId": "21212", "quantity": 54}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: orders-service