---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stocks-service
  name: stocks-service
  namespace: warehouse
spec:
  # replicas: ${REPLICAS}
  replicas: 1
  selector:
    matchLabels:
      app: stocks-service
  template:
    metadata:
      labels:
        app: stocks-service
    spec:
      containers:
      - image: quay.io/famargon/stocks-service-cloudevents-event-driven:latest
        imagePullPolicy: Always
        name: stocks-service
        env:
          - name: CE_BROKER_URL
            value: http://kafka-broker-ingress.knative-eventing.svc.cluster.local/warehouse/default
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGO_USER
            value: admin
          - name: MONGO_PWD
            value: password
          - name: MONGO_HOSTS
            value: mongo-database:27017
          - name: MONGO_TLS
            value: 'false'
          - name: MONGO_TLS_INSECURE
            value: 'false'
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8081
          initialDelaySeconds: 1
          periodSeconds: 15
          timeoutSeconds: 7
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stocks-service
  name: stocks-service
  namespace: warehouse
spec:
  ports:    
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: http
  selector:
    app: stocks-service
  type: ClusterIP
